{
 "title": "axon-benchmark",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(axon_consensus_height, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "jemalloc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "axon memory trace",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      { "expr": "axon_memory_trace" }
     ]
    },
    {
     "title": "axon db memory trace",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      { "expr": "axon_db_memory_trace" }
     ]
    }
   ]
  },
  { "title": "Axon logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Error logs display",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "json.message:error",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Round greater than or equal to 3",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "json.message: \"round\" AND json.message: [3 TO *]",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "error logs count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "json.message:error",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "TPS",
     "type": "graph",
     "description": "rate of committed transactions for each node in this network",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(rate(axon_consensus_committed_tx_total[5m]))",
       "legendFormat": "TPS"
      }
     ]
    },
    {
     "title": "exec_p90",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(histogram_quantile(0.90, sum(rate(axon_consensus_time_cost_seconds_bucket{type=\"exec\"}[5m])) by (le, node)))",
       "legendFormat": "exec_90"
      }
     ]
    },
    {
     "title": "consensus_round_cost",
     "type": "graph",
     "description": "lower is better, no data when all nodes consensus with round 0.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "(axon_consensus_round > 0 )", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "consensus_p90",
     "type": "graph",
     "description": "lower is better",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(histogram_quantile(0.90, sum(rate(axon_consensus_duration_seconds_bucket[5m])) by (le, node)))",
       "legendFormat": "time_usage(s)"
      }
     ]
    },
    {
     "title": "get_cf_each_block_time_usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg (sum by (instance) (increase(axon_storage_get_cf_seconds[5m]))) / avg(increase(axon_consensus_height[5m]))"
      }
     ]
    },
    {
     "title": "put_cf_each_block_time_usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg (sum by (instance) (increase(axon_storage_put_cf_seconds[5m]))) / avg(increase(axon_consensus_height[5m]))"
      }
     ]
    },
    {
     "title": "current_height",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sort_desc(axon_consensus_height)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "check_block_cost_p90",
     "type": "graph",
     "description": "lower is better",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(histogram_quantile(0.90, sum(rate(axon_consensus_check_block_bucket{type=\"check_block_cost\"}[5m])) by (le, node)))",
       "legendFormat": "check_block_cost"
      },
      {
       "expr": "avg(histogram_quantile(0.90, sum(rate(axon_consensus_check_block_bucket{type=\"write_wal_cost\"}[5m])) by (le, node)))",
       "legendFormat": "write_wal_cost"
      }
     ]
    },
    {
     "title": "synced_block",
     "type": "graph",
     "description": "lower is better. Number of blocks generated by the synchronization",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "axon_consensus_sync_block_total ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Liveness",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(axon_consensus_height{job=\"axon_exporter\"}[1m])",
       "legendFormat": "Liveness"
      }
     ]
    },
    {
     "title": "mempool_cached_tx",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "axon_mempool_tx_count", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "processed_tx_request",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(axon_api_request_result_total{type=\"eth_sendRawTransaction\"}[5m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(axon_api_request_result_total{result=\"success\",type=\"eth_sendRawTransaction\"}[5m]))",
       "legendFormat": "Success Total"
      },
      {
       "expr": "rate(axon_api_request_result_total{result=\"success\", type=\"eth_sendRawTransaction\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "processed_rpc_request",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(axon_api_request_result_total[5m])) by (type)",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(axon_api_request_result_total{result=\"success\"}[5m])) by (type)",
       "legendFormat": "Success Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "network_message_arrival_rate",
     "type": "graph",
     "description": "Estimate the network message arrival rate in the last five minutes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "(\n  # broadcast_count * (instance_count - 1)\n  sum(increase(axon_network_message_total{target=\"all\", direction=\"sent\"}[5m])) * (count(count by (instance) (axon_network_message_total)) - 1)\n  # unicast_count\n  + sum(increase(axon_network_message_total{target=\"single\", direction=\"sent\"}[5m]))\n) \n/\n# received_count\n(sum(increase(axon_network_message_total{direction=\"received\"}[5m])))\n"
      }
     ]
    },
    {
     "title": "Connected Peers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(axon_network_saved_peer_count)",
       "legendFormat": "Saved peers"
      },
      { "expr": "axon_network_connected_peers", "legendFormat": "Connected Peers" }
     ]
    },
    {
     "title": "Connected Peers",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "axon_network_connected_peers", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Connected Consensus Peers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(axon_network_tagged_consensus_peers)",
       "legendFormat": "Consensus peers"
      },
      {
       "expr": "axon_network_connected_consensus_peers",
       "legendFormat": "{{instance}}-Connected Consensus Peers (Minus itself)"
      }
     ]
    },
    {
     "title": "Connected Consensus Peers (Minus itself)",
     "type": "gauge",
     "description": "The right number should be total number of consensus peers minus 1 (Itself). For example, 9 consensus peers, then the right number should be 8.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "axon_network_connected_consensus_peers",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disconnected count(To other peers)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "axon_network_peer_id_disconnected_count",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Saved peers",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "axon_network_saved_peer_count", "legendFormat": "Saved peers" }
     ]
    },
    {
     "title": "Received messages in processing by peer_id",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "axon_network_received_peer_id_message_in_processing_guage"
      }
     ]
    },
    {
     "title": "Received messages in processing",
     "type": "gauge",
     "description": "Total number of received messages in processing",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "axon_network_received_message_in_processing_guage",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Received messages in processing by ip",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "axon_network_received_ip_message_in_processing_guage{instance=~\"$node\"}"
      }
     ]
    },
    {
     "title": "Connecting Peers",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "axon_network_outbound_connecting_peers",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Unidentified Connections",
     "type": "gauge",
     "description": "Processing identify protocol handshake, etc verify chain id.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "axon_network_unidentified_connections",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Ping (ms)_p90",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(histogram_quantile(0.90, sum(rate(axon_network_ping_in_ms_bucket[5m])) by (le, instance)))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}